name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron: "* * * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Create file in repository
        run: |
          date +%Y%m%d%H%M > ${{ github.workspace }}/date-$(date +%Y%m%d%H%M)
      - name: List files in the repository after
        run: |
          ls ${{ github.workspace }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Changed files
      - run: echo "🍏 This job's status is ${{ job.status }}."

